language: swift
osx_image: xcode10.2
xcode_project: GlitchLabel.xcodeproj
xcode_scheme: GlitchLabel
xcode_sdk: iphonesimulator
before_install:
    - gem install xcpretty
script:
    - set -o pipefail
    - xcodebuild -project $TRAVIS_XCODE_PROJECT -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK build | xcpretty
